import React from "react"
import type { Metadata } from "next"

import PagesLayout from "@/components/Layout/PagesLayout"

import "./globalStyles/index.scss"

export const metadata: Metadata = {
  title: "BookStore",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <PagesLayout>{children}</PagesLayout>
}
